require 5.002;

use File::Copy;
use strict;
use Socket;
use Carp;
use FileHandle;

# Used to generate tables of color information for things that can't directly use colorlist.dat




sub MakeReg
{
    my($file) = shift(@_);
    my($szRegColor);
    my($szReg4bpp);
    my($fInTPCBlock);

    open TABLE, "<$file" or die "cannot open file \"$file\"\n";

    print "; The following lines are generated by executing\n";
    print "; \"perl colorproc.pl reg colorlist.dat\" in ...\\public\\shellw\\oak\\inc.\n";
    print "; DON'T modify this here, modify colorlist.dat, re-run the script, and\n";
    print "; paste the result here!\n";
    print "[HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Color]\n";

    $szRegColor = "";
    $szReg4bpp = "";
    $fInTPCBlock = 0;
    while(<TABLE>)
        {
        if (/#ifdef TPC/)
            {
            $fInTPCBlock = 1;
            }

        if (/#else \/\/ TPC/)
            {
            $fInTPCBlock = 1 - $fInTPCBlock;
            }

        if (/#endif \/\/ TPC/)
            {
            $fInTPCBlock = 0;
            }

        if ( (($fInTPCBlock == 1) && ($ENV{IMGTPC})) || (($fInTPCBlock == 0) && !($ENV{IMGTPC})) )
        {

            if (/DEFINE_SHELL_COLOR\(([^\s,]*)[\s,]*([^\s,]*)[\s,]*RGB\(([^\s,]*)[\s,]*([^\s,]*)[\s,]*([^\s,]*)[\s,]*\),[\s]*RGB\(([^\s,]*)[\s,]*([^\s,]*)[\s,]*([^\s,]*)[\s,]*\)/)
                {
                printf "; %-25s Color-RGB(%3d, %3d, %3d) 4bpp-RGB(%3d, %3d, %3d) \n", $1, $3, $4, $5, $6, $7, $8;
                if($szRegColor)
                    {
                    $szRegColor = "$szRegColor,";
                    }
                $szRegColor = $szRegColor . sprintf("%02X,%02X,%02X,00", $3, $4, $5);

                if($szReg4bpp)
                    {
                    $szReg4bpp = "$szReg4bpp,";
                    }
                $szReg4bpp = $szReg4bpp . sprintf("%02X,%02X,%02X,00", $6, $7, $8);

                }
            }

        }


    print "IF IMG4BP !\n";
    if ($ENV{IMGTPC})
    {
	    print "\"DefSHColor\"=hex:$szRegColor\n";
    }
    print "\"SHColor\"=hex:$szRegColor\n";
    print "ENDIF\n";
    print "IF IMG4BP\n";
    if ($ENV{IMGTPC})
    {
	    print "\"DefSHColor\"=hex:$szReg4bpp\n";
    }
    print "\"SHColor\"=hex:$szReg4bpp\n";
    print "ENDIF\n";

    print "; END of stuff you shouldn't modify directly.\n";

    close TABLE
}


my($function) = shift;
if($function =~ m/reg/)
    {
    MakeReg(shift);
    }
elsif ($function =~ m/commctrl/)
    {
    print "NYI: Making table for commctrl_priv.h\n";
#    MakeCommctrl(shift);
    }


exit;
