#pragma once

#include "PingChecker.h"


// Log
#define IOCTL_WIFISVCMGR_LOG_SET_BUFFERSIZE		(0x1000)
#define IOCTL_WIFISVCMGR_LOG_GET_BUFFERSIZE		(0x1001)
#define IOCTL_WIFISVCMGR_LOG_ADD_LOGDATA		(0x1002)
#define IOCTL_WIFISVCMGR_LOG_FLUSH				(0x1003)



// PingChecker

#define IOCTL_WIFISVCMGR_PINGCHECKER_START		(0x2000)
#define IOCTL_WIFISVCMGR_PINGCHECKER_GET_STATUS	(0x2001)
#define IOCTL_WIFISVCMGR_PINGCHECKER_STOP		(0x2002)


// UnattendedMode Management
#define IOCTL_WIFISVCMGR_SET_UNATTENDEDMODE		(0x3000)



BOOL WSM_SetLogBufSize(DWORD dwSize);
BOOL WSM_AddLogData(LPTSTR strBuf);